### ISSUE TITLE
Missing module specification in codegen.yaml

### ISSUE THREAD

**Issue by matsbror** [wasmCloud/examples#51]
The ecommerce fakepay interface does not work with wapc version 0.0.4.
The following `codegen.yaml` seems to work but needs to be checked:

```
schema: payments.widl
generates:
  src/generated.rs:
    module: '@wapc/widl-codegen/rust'
    visitorClass: ModuleVisitor
  src/lib.rs:
    ifNotExists: true
    module: '@wapc/widl-codegen/rust'
    visitorClass: ScaffoldVisitor
    config:
      use: generated
```
